version: "3.7"

services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: coracoes_da_lila
            POSTGRES_USER: lila
            POSTGRES_PASSWORD: lila

            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - my-network

    # Add Server -> Connection -> Hostname/address
    # Set field to 172.17.0.1
    pgadmin:
            image: dpage/pgadmin4:latest
            restart: always
            environment:
                PGADMIN_DEFAULT_EMAIL: admin@email.com
                PGADMIN_DEFAULT_PASSWORD: lila
                PGADMIN_LISTEN_PORT: 80
            ports:
                - "8090:80"
            volumes:
                - pgadmin-data:/var/lib/pgadmin
            depends_on:
                - db
            networks:
                - my-network

networks: 
  my-network:
    driver: bridge

volumes:
    db-data:
    pgadmin-data:
