apiVersion: v1
kind: Service
metadata:
  name: stt-api-service
  namespace: dblab-stt
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3030"
    prometheus.io/path: "/metrics"
  labels:
    app: stt-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3030
      protocol: TCP
  selector:
    app: stt-api
